# Generated by Django 4.1 on 2022-08-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('pic', models.TextField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=18, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=10, null=True)),
                ('class_number', models.IntegerField(blank=True, null=True)),
                ('politics_statue', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college', models.CharField(blank=True, max_length=10, null=True)),
                ('tea_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('tea_name', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
    ]
